spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${ secrets.RDS_URL }
    username: ${ secrets.RDS_USERNAME }
    password: ${ secrets.RDS_PASSWORD }

  jpa:
    hibernate:
      ddl-auto: update # 초기 배포 확인용으로 update 사용.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false


  sql:
    init:
      mode: always
