spring:
  sql:
    init:
      mode: always      # 항상 schema.sql, data.sql 실행
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/Otboo
    driver-class-name: org.postgresql.Driver
    username: Otboo
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        generate_statistics: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
kma:
  service-key: ${KMA_KEY}
kakao:
  rest-key: ${KAKAO_KEY}



cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION:3600000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

logging:
  level:
    org:
      hibernate:
        sql: warn
        type.descriptor.sql: trace
