spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${{ secrets.RDS_URL }}
    username: ${{ secrets.RDS_USERNAME }}
    password: ${{ secrets.RDS_PASSWORD }}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSqlDialect
    open-in-view: false


  sql:
    init:
      mode: never
