spring:
  application:
    name: otboo
  profiles:
    active: dev
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

logging:
  level:
    root: info

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-custom-ui.html