name: github actions CI
on:
  pull_request:
    types: [opened]
    branches: ["dev", "main"]


jobs:
  steps:
    - name: actions/ cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-